apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'labsgit-lukaszk-hmcts-nodejs'
  description: "Deploying a Node.js application as a part of Golden Path tutorial"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_labsgit/labs-lukaszk-hmcts-nodejs
    github.com/project-slug: 'hmcts/labs-lukaszk-hmcts-nodejs'
  tags:
    - nodejs
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: service
  system: labsgit
  lifecycle: experimental
  owner: dts_cft_developers
